// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	instances: NamespaceInstancesTranslation
}

type RootTranslation = {
	/**
	 * G​l​o​w​s​q​u​i​d​ ​L​a​u​n​c​h​e​r
	 */
	title: string
}

export type NamespaceInstancesTranslation = {
	/**
	 * L​a​s​t​ ​p​l​a​y​e​d​ ​{​0​}
	 * @param {string} 0
	 */
	lastPlayed: RequiredParams<'0'>
	/**
	 * P​l​a​y
	 */
	play: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
}

export type Namespaces =
	| 'instances'

type DisallowNamespaces = {
	/**
	 * reserved for 'instances'-namespace\
	 * you need to use the `./instances/index.ts` file instead
	 */
	instances?: "[typesafe-i18n] reserved for 'instances'-namespace. You need to use the `./instances/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * Glowsquid Launcher
	 */
	title: () => LocalizedString
	instances: {
		/**
		 * Last played {0}
		 */
		lastPlayed: (arg0: string) => LocalizedString
		/**
		 * Play
		 */
		play: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
	}
}

export type Formatters = {}
