// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	account: NamespaceAccountTranslation,
	instances: NamespaceInstancesTranslation,
	settings: NamespaceSettingsTranslation
}

type RootTranslation = {
	/**
	 * G​l​o​w​s​q​u​i​d​ ​L​a​u​n​c​h​e​r
	 */
	title: string
}

export type NamespaceAccountTranslation = {
	/**
	 * N​o​b​o​d​y
	 */
	noAccountSelected: string
	/**
	 * S​e​l​e​c​t​ ​A​c​c​o​u​n​t
	 */
	select: string
	/**
	 * A​v​a​t​a​r​ ​f​o​r​ ​{​0​}
	 * @param {string} 0
	 */
	avatarFor: RequiredParams<'0'>
	/**
	 * A​d​d​ ​A​c​c​o​u​n​t
	 */
	add: string
	/**
	 * A​c​c​o​u​n​t​ ​S​e​t​t​i​n​g​s
	 */
	settings: string
}

export type NamespaceInstancesTranslation = {
	/**
	 * L​a​s​t​ ​p​l​a​y​e​d​ ​{​0​}
	 * @param {string} 0
	 */
	lastPlayed: RequiredParams<'0'>
	/**
	 * P​l​a​y
	 */
	play: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * A​d​d​ ​I​n​s​t​a​n​c​e
	 */
	add: string
}

export type NamespaceSettingsTranslation = {
	/**
	 * S​e​t​t​i​n​g​s
	 */
	name: string
}

export type Namespaces =
	| 'account'
	| 'instances'
	| 'settings'

type DisallowNamespaces = {
	/**
	 * reserved for 'account'-namespace\
	 * you need to use the `./account/index.ts` file instead
	 */
	account?: "[typesafe-i18n] reserved for 'account'-namespace. You need to use the `./account/index.ts` file instead."

	/**
	 * reserved for 'instances'-namespace\
	 * you need to use the `./instances/index.ts` file instead
	 */
	instances?: "[typesafe-i18n] reserved for 'instances'-namespace. You need to use the `./instances/index.ts` file instead."

	/**
	 * reserved for 'settings'-namespace\
	 * you need to use the `./settings/index.ts` file instead
	 */
	settings?: "[typesafe-i18n] reserved for 'settings'-namespace. You need to use the `./settings/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * Glowsquid Launcher
	 */
	title: () => LocalizedString
	account: {
		/**
		 * Nobody
		 */
		noAccountSelected: () => LocalizedString
		/**
		 * Select Account
		 */
		select: () => LocalizedString
		/**
		 * Avatar for {0}
		 */
		avatarFor: (arg0: string) => LocalizedString
		/**
		 * Add Account
		 */
		add: () => LocalizedString
		/**
		 * Account Settings
		 */
		settings: () => LocalizedString
	}
	instances: {
		/**
		 * Last played {0}
		 */
		lastPlayed: (arg0: string) => LocalizedString
		/**
		 * Play
		 */
		play: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Add Instance
		 */
		add: () => LocalizedString
	}
	settings: {
		/**
		 * Settings
		 */
		name: () => LocalizedString
	}
}

export type Formatters = {}
